#!/usr/bin/env ansible-playbook

- hosts: 127.0.0.1
  connection: local
  become: yes
  tasks:
    - block:
        - name: Show lxd profile
          shell: lxc profile show juju-cli
      rescue:
        - name: Create lxd profile
          shell: lxc profile create juju-cli
    - name: Configure lxd profile
      shell: |
         cat profiles/juju-cli.yaml | lxc profile edit juju-cli

